### ISSUE TITLE
Support all Kubernetes fields in Probe schema

### ISSUE THREAD

**Issue by brendanmaguire** [strimzi/strimzi-kafka-operator#1645]
It does not seem to be possible to set the `periodSeconds`, `successThreshold` and `failureThreshold` values via the container probes.

It would be great if the [Strimzi Probe Schema](https://strimzi.io/docs/latest/#type-Probe-reference) supported all the [Kubernetes fields](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)

**Additional context**
I would like to set the `failureThreshold` to a high value in order to allow Kafka nodes recover after a hard shutdown. If there is sufficient data stored on the node then it cannot clean up the logs before the failure threshold is reached and the pod is terminated. This causes a `CrashLoopBackOff`.

Maybe there are alternative ways of preventing this, but the most obvious solution to me would be to facilitate the passing through of the `failureThreshold` parameter.

**Comment by tombentley** [comment]
The readiness probe on the pods has been changed on master to allow precisely this log recovery. We're expecting to release 0.12.0 pretty soon which will have this change.

**Comment by scholzj** [comment]
As @tombentley pointed out, this should be addressed in master now. But let's keep this issue open, I had this anyway on my private TODO list. So we can have it tracked here.

**Comment by brendanmaguire** [comment]
Thanks for the prompt responses.

I guess you are referring to the commit, 1b42d8cba991daf008ebcfe129078f05601da471 . I may be reading it wrong but it seems this will only facilitate the readiness probe checking the broker is running and no longer recovering log files. It will not change the overall behavior of the pod as the readiness probe will still fail after the same period of time (`initialDelaySeconds + (periodSeconds + timeoutSeconds) * failureThreshold`), where we can only configure `initialDelaySeconds` and `timeoutSeconds`. I'm unsure how this will fix the issue of allowing sufficient time for log recovery on pods with more data than can be recovered within that period?
