### ISSUE TITLE
[Question] Can I have a new serviceAccount in kafkaConnect spec ?

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3179]
**_[preface]_**: I am using Camel-s3-sink-connector using Strimzi kafka connect to push data from remote Kafka server to S3. 

I wanted to authenticate S3 using IAM role instead of access key and secret (ref: https://developers.redhat.com/blog/2020/02/14/using-secrets-in-apache-kafka-connect-configuration/)

Plan is to create a serviceAccount and create a aws IAM role for that serviceAccount (which has access to S3) and assign the serviceAccount in KafkaConnect yaml file.

I know that strimzi kafkaconnect internally create a service Account. Can I use additional service account in kafkaconnect definition? or how to edit the internal serviceAccount ?

**Comment by scholzj** [comment]
Correct me if I'm wrong, but I do not think there is any notion of additional service account - each pod can have only one service account. I guess that if you create the service account with the right name and settings before deploying the Connect custom resource, we might just reuse it. But I never tried it TBH.

**Comment by geota** [comment]
I am in this same boat. We would like a way to provide a service account for KafkaConnect to use or provide additional annotations that yall would reflect onto the ServiceAccount you create.

**Comment by scholzj** [comment]
Have you tried what I suggested above?

**Comment by saranyaeu2987** [comment]
@saranyaeu2987 

I did 2 ways and neither worked.

1st way:
1. Deployed KafkaConnect deployment file to autocreate serviceaccount. Edited the serviceaccount to add the following IAM role annotation. Redeployed KafkaConnect deployment.

2nd way:
I deployed below serviceaccount followed  by kafkaconnect. Kafkaconnect used the created serviceaccount but still encountered **Access Denied** issue to S3
```
apiVersion: v1. 
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: <arn>
  creationTimestamp: "2020-06-17T21:48:25Z"
  labels:
    app.kubernetes.io/instance: emd-kafka-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka-connect
    app.kubernetes.io/part-of: strimzi-emd-kafka-cluster
    strimzi.io/cluster: emd-kafka-cluster
    strimzi.io/kind: KafkaConnect
    strimzi.io/name: strimzi
  name: emd-kafka-cluster-connect
  namespace: default
  resourceVersion: "855936"
  selfLink: /api/v1/namespaces/default/serviceaccounts/emd-kafka-cluster-connect
  uid: 24bdb5d3-1d43-4bf6-b883-b275b0f5397e
secrets:
- name: emd-kafka-cluster-connect-token-glprh
```

What am I missing here. Any suggestions will be appreciated.

**Comment by scholzj** [comment]
So, in the second case - after you deployed the KafkaConnect resource and the operator deployed it - was the `eks` annotation still present? Or did the operator removed it?

**Comment by saranyaeu2987** [comment]
Edited previous comment.

eks annotation was still present after kafkaconnect deployment!!

_( But like I mentioned before, I removed ownerReferences spec, since I wasnt able to create serviceaccount with that. Unsure if thats related or not.)_

**Comment by scholzj** [comment]
That actually surprises me. I would have expected that the operator would remove the annotations which would be the probably cause. If the annotation is still there, it is a bit weird and I'm not sure if we have anything to do with it. 

How is the annotation actuall supposed to work? Does it tell some EKS stuff in the background to hack around the networks of the pods with this service account and show it the right instance metadata corresponding to the given IAM role? Or does it use some other mechanism?

Following on that - how do you test whether it gives you the S3 access or not? Are you using some S3 connector? Are you sure that it can get the IAM role whatever way EKS distributes it?

**Comment by saranyaeu2987** [comment]
@scholzj 

> How is the annotation actuall supposed to work? Does it tell some EKS stuff in the background to hack around the networks of the pods with this service account and show it the right instance metadata corresponding to the given IAM role? Or does it use some other mechanism?

Yes, that annotation creates a webhook on the cluster and watches for pods that are associated with service accounts with this annotation and creates environment  variables for auth

> Following on that - how do you test whether it gives you the S3 access or not? Are you using some S3 connector? Are you sure that it can get the IAM role whatever way EKS distributes it?

The serviceaccount was tested in different aws-cli pod which has following definition
```
apiVersion: v1
kind: Pod
metadata:
  name: awsclitest
spec:
  serviceAccountName: emd-kafka-cluster-connect <-- serviceaccount which has that eks.amazonaws.com/role-arn .
  automountServiceAccountToken: false
  containers:
    - name: hello-aws-cli
      image: amazon/aws-cli
      command: ['sh', '-c', 'aws sts get-caller-identity && sleep 3600']
  volumes:
  - name: test-storage
    emptyDir: {}
```
I can see contents of bucket by running **aws s3 ls <bucket>** in pod shell

**Comment by scholzj** [comment]
> Yes, that annotation creates a webhook on the cluster and watches for pods that are associated with service accounts with this annotation and creates environment variables for auth (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html)

So, are the environment variables present in the pods? Injecting env vars might not be easy with operator which might tend to overwrite them.

**Comment by saranyaeu2987** [comment]
Yes, They are present in the pod

[kafka@emd-kafka-cluster-connect-c56f8964d-5l5b5 kafka]$ printenv |grep AWS
AWS_ROLE_ARN=arn:aws:iam::<role>/emd-kafka-cluster-connect
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

**Comment by scholzj** [comment]
Ok, so they are there. But the Camel-s3-sink-connector does not work. Is that correct? Are you sure the connector actually supports this? I mean it would need to understand these env vars, look for them and be able to load and use the token.

**Comment by saranyaeu2987** [comment]
> Are you sure the connector actually supports this?
Not sure. Atleast as per https://github.com/apache/camel-kafka-connector/issues/267#issuecomment-642072485 they said it should work.
Asked them again https://github.com/apache/camel-kafka-connector/issues/282

**Comment by scholzj** [comment]
I think the answer in apache/camel-kafka-connector#282 suggests that this is not supported. They can work with the EC2 Instance Metadata, but this tool seems to provide some other way and TBH I haven't seen it yet. Usually I saw something like kube2Iam which emulates the EC2 instance metadata.

**Comment by geota** [comment]
@scholzj This really should just be ensuring the underlying Java SDK that the Camel Kafka connector sinks uses are updated to a version that has support for AWS_WEB_IDENTITY_TOKEN_FILE env var. This should just be crawled in the DefaultCredentialProvider chain that the SDK executes to find credentials. Support in the Java SDK was shipped in [2.10.11 ](https://github.com/aws/aws-sdk-java-v2/issues/1470#issuecomment-551282144).

It looks like @valdar commented in the other thread that this is supported in a newer version of camel-kafka-connector. 

To be clear, this is the official AWS supported way of providing role base credentials to pods. 

See:
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by scholzj** [comment]
> To be clear, this is the official AWS supported way of providing role base credentials to pods.

If you ask me, maybe they shouldn't have created yet another way to deal with it :-). But at least I learned something new. Thanks for explaining.

But as far as I understood, it seems to work fine with Strimzi and the only problem is in the connector using the environment variables this sets. So I think we can close this?

**Comment by geota** [comment]
@scholzj i think you are correct. we can close this out.

**Comment by valdar** [comment]
@scholzj I think so, hoping that aws sdk 2.10.11 dose its job.

**Comment by scholzj** [comment]
Thanks. I will close it, if there is anything else you can just reopen it or open a new one.

**Comment by vagharsh** [comment]
i am new to deploying kafka using strimzi .. could someone please provide a documentation on how can i add annotation to the service accounts mentioned in this document https://strimzi.io/docs/operators/latest/deploying#ref-operator-cluster-rbac-resources-str

my k8s cluster is in AWS EKS and i want to push my kafka-connect knd image to ECR and then use that image as connector.. 
also in my connector i am accessing AWS secrets manager so i would need to access couple of other AWS resources as well . so assigning annotations to the service accounts that the operator is creating is crucial for me .. 
unfortunately i couldn't find what i am looking for. 

i add annotation to the service account and a minute later the annotation was gone . and that's how i arrived to this github issue page.

if adding annotation to the service account while creation is not possible, then is it possible to use another service account that i have manually created instead of the one that the operator had created .. 

i really appreciate any detailed examples or samples .. if required i can provide my kafkaConnect and kafkaConnector kind yamls.

thanks

**Comment by scholzj** [comment]
@vagharsh You should checkout this section: https://strimzi.io/docs/operators/latest/full/deploying.html#assembly-customizing-kubernetes-resources-str => you can essentially do it in the `KafkaConnect` custom resource in `.spec.template`.

**Comment by vagharsh** [comment]
thanks @scholzj .. although this document was very much helpful on the api specs of all resources https://github.com/strimzi/strimzi-kafka-operator/blob/main/documentation/modules/appendix_crds.adoc#type-KafkaConnectSpec-schema-{context}

now the service account which is being created by the kafkaconnect <debezium-cluster-name>-connect has the annotation .. 

but there is another service account is being created as well <debezium-cluster-name>-connect-build  this is the service account i need to provide annotations as well .. i could not find where to add what in which file to add for that service account as well .. 

what am i missing ?

**Comment by scholzj** [comment]
If you check the template section for the Kafka Connect resource, you will see it has two fields: `buildServiceAccount` and `serviceAccount`. `buildServiceAccount` is used during the build of the new image. `serviceAccount` is used while Kafka Connect is running.

**Comment by vagharsh** [comment]
found it ... thank youuu

**Comment by gtsopour** [comment]
@scholzj @vagharsh One quick question please and thanks in advance for your support. I have found the sections for the serviceAccount and the buildServiceAccount but how I can refer an existing ServiceAccount in the [MetadataTemplate schema properties](https://strimzi.io/docs/operators/latest/configuring.html#type-MetadataTemplate-schema-reference)? Thanks in advance for your support.

**Comment by scholzj** [comment]
You can only configure some additional metadata for the service account. You cannot use your own custom service account.

**Comment by scholzj** [comment]
I have never done it. So I do not really know. The YAMl you shared will put this annotation to the Service Account. so if you have some other tooling that will give the service account the AWS role based on that, it might work.
